# Server configuration
server.port=8080

# Logging configuration
logging.level.ru.yandex.practicum.filmorate=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.jdbc.core=DEBUG

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql